[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "discord-py>=2.5.2",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
]
